[package]
name = "saphir"
version = "0.3.2"
authors = ["richer <richer.arc@gmail.com>"]
description = "Yet another http server framework based on Hyper-rs"
documentation = "https://docs.rs/saphir"
homepage = "https://github.com/richerarc/saphir"
repository = "https://github.com/richerarc/saphir"
keywords = ["hyper", "http", "server", "web"]
license = "MIT"

[dependencies]
log = "0.4.1"
hyper = "0.12"
hyperx = "0.12"
http = "0.1"
futures = "0.1"
tokio = "0.1"
regex = "1.0"
chrono = "0.4"
ansi_term = "0.11"
url = "1.7"
bytes = "0.4"

[[test]]
name = "server"
path = "tests/http_server.rs"