[package]
name = "saphir"
version = "0.6.0"
authors = ["richer <richer.arc@gmail.com>"]
description = "Yet another http server framework based on Hyper-rs"
documentation = "https://docs.rs/saphir"
homepage = "https://github.com/richerarc/saphir"
repository = "https://github.com/richerarc/saphir"
readme = "README.md"
keywords = ["hyper", "http", "server", "web"]
license = "MIT"

[features]

default = []
https = ["rustls", "tokio-rustls"]

[dependencies]
log = "~0.4.6"
hyper = "~0.12.14"
hyperx = "~0.13.1"
http = "~0.1.13"
futures = "~0.1.25"
regex = "~1.0.6"
ansi_term = "~0.11.0"
tokio = "~0.1.11"
parking_lot = "~0.6.4"
rayon = "1.0.3"

rustls = { version = "~0.14.0", optional = true }
tokio-rustls = { version = "~0.8.0", optional = true }

[[test]]
name = "server"
path = "tests/http_server.rs"